# Generated by Django 3.2.9 on 2022-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220804_1336'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='restaurant_menu', to='menu.Menu'),
        ),
    ]
